version: '2.2'

services:
  test-read-write-db:
    image: postgres
    container_name: read-write-db
    environment:
      - POSTGRES_USER=db_read_write
      - POSTGRES_PASSWORD=12345
    restart: always
    volumes:
      - D:/project/data_1/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  test-read-db:
    image: postgres
    container_name: read-db
    environment:
      - POSTGRES_USER=db_read
      - POSTGRES_PASSWORD=12345
    restart: always
    volumes:
      - D:/project/data_2/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
